In [1]:
import pandas as pd
import numpy as np

In [ ]:
comp = pd.read_excel('c')
comp

,Study,Project 04,Requester 04,Sample 04,Papp AB 04,Papp BA 04,Efflux 04,Recovery AB 04,Recovery BA 04,Unnamed: 9,...,Recovery AB 02,Recovery BA 02,Unnamed: 19,Study all,Sample all,Papp AB all,Papp BA all,Efflux all,Recovery AB all,Recovery BA all
0,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00014925-16,NaN,1.035356,NaN,NaN,21.296849,NaN,...,NaN,14.39,NaN,Average Total MDCK studies,NCGC00014925,6.310000,4.767500,9.780000,76.400000,67.370000
1,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00015205-09,14.759865,16.377504,1.105507,63.779625,56.357400,NaN,...,75.34,61.21,NaN,Average Total MDCK studies,NCGC00015205,9.977500,39.987500,3.637500,66.672500,68.542500
2,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00015608-17,NaN,13.815982,NaN,NaN,50.975471,NaN,...,440.31,122.85,NaN,Average Total MDCK studies,NCGC00015608,2.184534,5.294789,2.848797,44.474266,22.685421
3,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00015735-11,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00015735,1.530000,12.405000,11.360000,58.000000,67.000000
4,AUTO-MDCK-2026-04,cell automation,Propranolol,NCGC00015798-07,13.254151,11.994251,0.904930,44.181691,55.489506,NaN,...,54.50,67.05,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN
5,AUTO-MDCK-2026-04,cell automation,Propranolol,NCGC00015798-13,15.397481,19.242439,1.296996,46.832092,84.483024,NaN,...,117.34,64.50,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN
6,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00015876-11,NaN,2.409773,NaN,NaN,162.991029,NaN,...,NaN,54.96,NaN,Average Total MDCK studies,NCGC00015876,0.143512,0.070816,0.553089,78.813519,33.223767
7,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00024379-16,NaN,10.094294,NaN,NaN,86.832928,NaN,...,NaN,66.54,NaN,Average Total MDCK studies,NCGC00024379,0.605000,5.705000,9.375000,73.000000,48.000000
8,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00092309-01,2.324933,2.914440,1.274454,38.527002,55.501192,NaN,...,38.80,71.70,NaN,Average Total MDCK studies,NCGC00092309,0.340000,1.320000,3.905000,65.500000,59.500000
9,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00092666-05,17.774617,14.577106,0.829049,49.731197,53.463811,NaN,...,73.58,67.97,NaN,Average Total MDCK studies,NCGC00092666,18.485000,23.795000,1.285000,97.000000,81.500000
10,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00125676-02,8.734205,21.552202,2.544334,72.181705,69.273376,NaN,...,96.04,76.37,NaN,Average Total MDCK studies,NCGC00125676,5.960000,17.149765,2.939828,75.333333,74.666667
11,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00128751-05,7.999619,5.727386,0.717083,84.048260,69.252194,NaN,...,NaN,76.02,NaN,Average Total MDCK studies,NCGC00128751,7.366667,11.155000,1.453333,80.260000,67.983333
12,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00159456-06,NaN,17.856275,NaN,NaN,86.448375,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00159456,1.025000,59.440000,60.990000,58.920000,64.600000
13,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00162413-13,NaN,NaN,NaN,NaN,NaN,NaN,...,356.19,189.18,NaN,Average Total MDCK studies,NCGC00162413,NaN,NaN,NaN,NaN,NaN
14,AUTO-MDCK-2026-04,cell automation,Talinolol,NCGC00164542-02,NaN,5.120559,NaN,NaN,66.763448,NaN,...,77.59,67.70,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN
15,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00164574-11,14.416041,19.774029,1.371540,81.591115,63.350082,NaN,...,91.90,67.65,NaN,Average Total MDCK studies,NCGC00164574,3.625000,11.245000,3.120000,64.500000,57.000000
16,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00164631-09,2.349956,5.696382,2.440030,39.029369,47.491266,NaN,...,38.18,60.23,NaN,Average Total MDCK studies,NCGC00164631,0.630000,4.645000,14.980000,50.000000,56.000000
17,AUTO-MDCK-2026-04,cell automation,Quinidine,NCGC00166281-06,4.360277,19.869894,4.548036,45.743777,34.046891,NaN,...,54.62,48.59,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN
18,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00168772-06,NaN,13.800888,NaN,NaN,49.474405,NaN,...,NaN,67.71,NaN,Average Total MDCK studies,NCGC00168772,0.705000,11.045000,16.300000,62.500000,63.500000
19,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00182410-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00182410,0.130000,0.020000,0.160000,13.500000,13.000000
20,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00182825-01,5.407864,7.331614,1.355746,75.222411,60.742017,NaN,...,NaN,54.61,NaN,Average Total MDCK studies,NCGC00182825,2.255000,7.035000,3.115000,72.500000,52.500000
21,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00188346-04,6.086715,16.544481,2.754825,51.187255,61.224733,NaN,...,NaN,52.32,NaN,Average Total MDCK studies,NCGC00188346,0.075000,5.910000,81.210000,37.500000,31.000000
22,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00188399-16,NaN,0.050717,NaN,NaN,62.607513,NaN,...,NaN,60.93,NaN,Average Total MDCK studies,NCGC00188399,0.400000,16.795000,43.850000,80.000000,69.500000
23,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00241101-07,NaN,5.153277,NaN,NaN,94.856258,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00241101,NaN,1.575000,NaN,NaN,51.000000
24,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00241102-10,NaN,2.053366,NaN,NaN,62.797376,NaN,...,56.27,62.31,NaN,Average Total MDCK studies,NCGC00241102,0.220000,1.590000,9.250000,54.500000,60.000000
25,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00241107-02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00241107,0.210000,7.710000,42.375000,77.000000,74.000000
26,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00242478-13,NaN,30.014449,NaN,NaN,72.612629,NaN,...,93.09,86.24,NaN,Average Total MDCK studies,NCGC00242478,0.280000,26.745000,104.785000,74.500000,66.500000
27,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00245963-02,NaN,NaN,NaN,NaN,NaN,NaN,...,28.15,57.33,NaN,Average Total MDCK studies,NCGC00245963,5.360000,10.600000,1.995000,77.000000,62.000000
28,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00247785-06,0.388579,2.792034,6.867354,40.254414,NaN,NaN,...,51.55,106.89,NaN,Average Total MDCK studies,NCGC00247785,0.280000,4.370000,15.925000,61.000000,67.500000
29,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00247877-09,28.839628,33.369496,1.181195,88.173662,72.268444,NaN,...,54.09,36.76,NaN,Average Total MDCK studies,NCGC00247877,12.520000,18.975000,1.510000,73.000000,57.000000
30,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00247879-05,2.268562,22.238224,12.348840,78.456955,48.518719,NaN,...,NaN,70.58,NaN,Average Total MDCK studies,NCGC00247879,1.335000,25.130000,18.845000,70.500000,68.000000
31,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00249685-18,NaN,0.221735,NaN,NaN,36.862807,NaN,...,NaN,46.18,NaN,Average Total MDCK studies,NCGC00249685,NaN,NaN,NaN,NaN,NaN
32,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00250135-11,NaN,0.298515,NaN,NaN,NaN,NaN,...,53.59,59.51,NaN,Average Total MDCK studies,NCGC00250135,8.060000,3.396667,1.034000,58.236000,43.545000
33,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00250218-02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00250218,NaN,NaN,NaN,NaN,NaN
34,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00263104-03,6.184382,NaN,NaN,NaN,NaN,NaN,...,NaN,69.54,NaN,Average Total MDCK studies,NCGC00263104,NaN,0.370000,NaN,NaN,45.500000
35,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00263156-13,1.059298,34.515578,35.510061,64.543452,80.351544,NaN,...,67.88,52.74,NaN,Average Total MDCK studies,NCGC00263156,0.545000,13.150000,24.190000,59.500000,66.500000
36,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00263623-03,NaN,0.398140,NaN,NaN,18.450910,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00263623,NaN,NaN,NaN,NaN,NaN
37,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00263912-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00263912,NaN,NaN,NaN,NaN,NaN
38,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00344093-03,NaN,6.121803,NaN,NaN,62.630543,NaN,...,NaN,73.72,NaN,Average Total MDCK studies,NCGC00344093,NaN,3.630000,NaN,NaN,57.500000
39,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00344622-09,4.470980,17.721007,9.366972,82.173602,73.206311,NaN,...,96.51,74.42,NaN,Average Total MDCK studies,NCGC00344622,NaN,14.915000,NaN,NaN,73.500000
40,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00345880-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,54.19,NaN,Average Total MDCK studies,NCGC00345880,2.215000,32.660000,14.745000,43.035000,69.500000
41,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00346569-03,2.190299,19.771706,12.411031,36.007166,60.034384,NaN,...,47.48,31.53,NaN,Average Total MDCK studies,NCGC00346569,NaN,10.275000,NaN,NaN,60.000000
42,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00346674-03,3.967616,10.426635,2.625557,54.906478,60.732730,NaN,...,65.87,50.43,NaN,Average Total MDCK studies,NCGC00346674,2.495000,12.675000,5.310000,67.000000,69.500000
43,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00346678-08,1.118764,12.502688,11.502333,77.361360,67.199482,NaN,...,96.38,75.19,NaN,Average Total MDCK studies,NCGC00346678,38.675000,13.630000,0.355000,125.500000,67.500000
44,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00346704-05,NaN,23.016027,NaN,NaN,51.710582,NaN,...,418.85,67.48,NaN,Average Total MDCK studies,NCGC00346704,4.290000,12.040000,3.285000,74.000000,44.000000
45,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00347064-02,NaN,0.750786,NaN,NaN,58.365465,NaN,...,61.15,70.99,NaN,Average Total MDCK studies,NCGC00347064,1.517500,9.130000,6.725000,53.000000,54.500000
46,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00348147-04,3.187279,17.979592,5.789142,105.401946,65.822874,NaN,...,98.61,70.57,NaN,Average Total MDCK studies,NCGC00348147,2.517738,31.599763,21.265194,81.122566,55.120514

In [12]:
comp["No AB 04 high BA 04"] = np.where(
    comp["Papp AB 04"].isna() & (comp["Papp BA 04"] >= 6),
    "no AB high BA",
    "INV"
)
comp["No AB 02 high BA 02"] = np.where(
    comp["Papp AB 02"].isna() & (comp["Papp BA 02"] >= 6),
    "no AB high BA",
    "INV"
)
comp

,Study,Project 04,Requester 04,Sample 04,Papp AB 04,Papp BA 04,Efflux 04,Recovery AB 04,Recovery BA 04,Unnamed: 9,...,Unnamed: 19,Study all,Sample all,Papp AB all,Papp BA all,Efflux all,Recovery AB all,Recovery BA all,No AB 04 high BA 04,No AB 02 high BA 02
0,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00014925-16,NaN,1.035356,NaN,NaN,21.296849,NaN,...,NaN,Average Total MDCK studies,NCGC00014925,6.310000,4.767500,9.780000,76.400000,67.370000,INV,INV
1,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00015205-09,14.759865,16.377504,1.105507,63.779625,56.357400,NaN,...,NaN,Average Total MDCK studies,NCGC00015205,9.977500,39.987500,3.637500,66.672500,68.542500,INV,INV
2,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00015608-17,NaN,13.815982,NaN,NaN,50.975471,NaN,...,NaN,Average Total MDCK studies,NCGC00015608,2.184534,5.294789,2.848797,44.474266,22.685421,no AB high BA,INV
3,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00015735-11,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00015735,1.530000,12.405000,11.360000,58.000000,67.000000,INV,INV
4,AUTO-MDCK-2026-04,cell automation,Propranolol,NCGC00015798-07,13.254151,11.994251,0.904930,44.181691,55.489506,NaN,...,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN,INV,INV
5,AUTO-MDCK-2026-04,cell automation,Propranolol,NCGC00015798-13,15.397481,19.242439,1.296996,46.832092,84.483024,NaN,...,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN,INV,INV
6,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00015876-11,NaN,2.409773,NaN,NaN,162.991029,NaN,...,NaN,Average Total MDCK studies,NCGC00015876,0.143512,0.070816,0.553089,78.813519,33.223767,INV,INV
7,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00024379-16,NaN,10.094294,NaN,NaN,86.832928,NaN,...,NaN,Average Total MDCK studies,NCGC00024379,0.605000,5.705000,9.375000,73.000000,48.000000,no AB high BA,INV
8,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00092309-01,2.324933,2.914440,1.274454,38.527002,55.501192,NaN,...,NaN,Average Total MDCK studies,NCGC00092309,0.340000,1.320000,3.905000,65.500000,59.500000,INV,INV
9,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00092666-05,17.774617,14.577106,0.829049,49.731197,53.463811,NaN,...,NaN,Average Total MDCK studies,NCGC00092666,18.485000,23.795000,1.285000,97.000000,81.500000,INV,INV
10,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00125676-02,8.734205,21.552202,2.544334,72.181705,69.273376,NaN,...,NaN,Average Total MDCK studies,NCGC00125676,5.960000,17.149765,2.939828,75.333333,74.666667,INV,INV
11,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00128751-05,7.999619,5.727386,0.717083,84.048260,69.252194,NaN,...,NaN,Average Total MDCK studies,NCGC00128751,7.366667,11.155000,1.453333,80.260000,67.983333,INV,INV
12,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00159456-06,NaN,17.856275,NaN,NaN,86.448375,NaN,...,NaN,Average Total MDCK studies,NCGC00159456,1.025000,59.440000,60.990000,58.920000,64.600000,no AB high BA,INV
13,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00162413-13,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00162413,NaN,NaN,NaN,NaN,NaN,INV,INV
14,AUTO-MDCK-2026-04,cell automation,Talinolol,NCGC00164542-02,NaN,5.120559,NaN,NaN,66.763448,NaN,...,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN,INV,INV
15,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00164574-11,14.416041,19.774029,1.371540,81.591115,63.350082,NaN,...,NaN,Average Total MDCK studies,NCGC00164574,3.625000,11.245000,3.120000,64.500000,57.000000,INV,INV
16,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00164631-09,2.349956,5.696382,2.440030,39.029369,47.491266,NaN,...,NaN,Average Total MDCK studies,NCGC00164631,0.630000,4.645000,14.980000,50.000000,56.000000,INV,INV
17,AUTO-MDCK-2026-04,cell automation,Quinidine,NCGC00166281-06,4.360277,19.869894,4.548036,45.743777,34.046891,NaN,...,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN,INV,INV
18,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00168772-06,NaN,13.800888,NaN,NaN,49.474405,NaN,...,NaN,Average Total MDCK studies,NCGC00168772,0.705000,11.045000,16.300000,62.500000,63.500000,no AB high BA,no AB high BA
19,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00182410-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00182410,0.130000,0.020000,0.160000,13.500000,13.000000,INV,INV
20,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00182825-01,5.407864,7.331614,1.355746,75.222411,60.742017,NaN,...,NaN,Average Total MDCK studies,NCGC00182825,2.255000,7.035000,3.115000,72.500000,52.500000,INV,INV
21,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00188346-04,6.086715,16.544481,2.754825,51.187255,61.224733,NaN,...,NaN,Average Total MDCK studies,NCGC00188346,0.075000,5.910000,81.210000,37.500000,31.000000,INV,no AB high BA
22,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00188399-16,NaN,0.050717,NaN,NaN,62.607513,NaN,...,NaN,Average Total MDCK studies,NCGC00188399,0.400000,16.795000,43.850000,80.000000,69.500000,INV,INV
23,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00241101-07,NaN,5.153277,NaN,NaN,94.856258,NaN,...,NaN,Average Total MDCK studies,NCGC00241101,NaN,1.575000,NaN,NaN,51.000000,INV,INV
24,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00241102-10,NaN,2.053366,NaN,NaN,62.797376,NaN,...,NaN,Average Total MDCK studies,NCGC00241102,0.220000,1.590000,9.250000,54.500000,60.000000,INV,INV
25,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00241107-02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00241107,0.210000,7.710000,42.375000,77.000000,74.000000,INV,INV
26,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00242478-13,NaN,30.014449,NaN,NaN,72.612629,NaN,...,NaN,Average Total MDCK studies,NCGC00242478,0.280000,26.745000,104.785000,74.500000,66.500000,no AB high BA,INV
27,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00245963-02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00245963,5.360000,10.600000,1.995000,77.000000,62.000000,INV,INV
28,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00247785-06,0.388579,2.792034,6.867354,40.254414,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00247785,0.280000,4.370000,15.925000,61.000000,67.500000,INV,INV
29,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00247877-09,28.839628,33.369496,1.181195,88.173662,72.268444,NaN,...,NaN,Average Total MDCK studies,NCGC00247877,12.520000,18.975000,1.510000,73.000000,57.000000,INV,INV
30,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00247879-05,2.268562,22.238224,12.348840,78.456955,48.518719,NaN,...,NaN,Average Total MDCK studies,NCGC00247879,1.335000,25.130000,18.845000,70.500000,68.000000,INV,no AB high BA
31,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00249685-18,NaN,0.221735,NaN,NaN,36.862807,NaN,...,NaN,Average Total MDCK studies,NCGC00249685,NaN,NaN,NaN,NaN,NaN,INV,INV
32,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00250135-11,NaN,0.298515,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00250135,8.060000,3.396667,1.034000,58.236000,43.545000,INV,INV
33,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00250218-02,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00250218,NaN,NaN,NaN,NaN,NaN,INV,INV
34,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00263104-03,6.184382,NaN,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00263104,NaN,0.370000,NaN,NaN,45.500000,INV,INV
35,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00263156-13,1.059298,34.515578,35.510061,64.543452,80.351544,NaN,...,NaN,Average Total MDCK studies,NCGC00263156,0.545000,13.150000,24.190000,59.500000,66.500000,INV,INV
36,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00263623-03,NaN,0.398140,NaN,NaN,18.450910,NaN,...,NaN,Average Total MDCK studies,NCGC00263623,NaN,NaN,NaN,NaN,NaN,INV,INV
37,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00263912-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00263912,NaN,NaN,NaN,NaN,NaN,INV,INV
38,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00344093-03,NaN,6.121803,NaN,NaN,62.630543,NaN,...,NaN,Average Total MDCK studies,NCGC00344093,NaN,3.630000,NaN,NaN,57.500000,no AB high BA,no AB high BA
39,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00344622-09,4.470980,17.721007,9.366972,82.173602,73.206311,NaN,...,NaN,Average Total MDCK studies,NCGC00344622,NaN,14.915000,NaN,NaN,73.500000,INV,INV
40,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00345880-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Average Total MDCK studies,NCGC00345880,2.215000,32.660000,14.745000,43.035000,69.500000,INV,INV
41,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00346569-03,2.190299,19.771706,12.411031,36.007166,60.034384,NaN,...,NaN,Average Total MDCK studies,NCGC00346569,NaN,10.275000,NaN,NaN,60.000000,INV,INV
42,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00346674-03,3.967616,10.426635,2.625557,54.906478,60.732730,NaN,...,NaN,Average Total MDCK studies,NCGC00346674,2.495000,12.675000,5.310000,67.000000,69.500000,INV,INV
43,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00346678-08,1.118764,12.502688,11.502333,77.361360,67.199482,NaN,...,NaN,Average Total MDCK studies,NCGC00346678,38.675000,13.630000,0.355000,125.500000,67.500000,INV,INV
44,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00346704-05,NaN,23.016027,NaN,NaN,51.710582,NaN,...,NaN,Average Total MDCK studies,NCGC00346704,4.290000,12.040000,3.285000,74.000000,44.000000,no AB high BA,INV
45,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00347064-02,NaN,0.750786,NaN,NaN,58.365465,NaN,...,NaN,Average Total MDCK studies,NCGC00347064,1.517500,9.130000,6.725000,53.000000,54.500000,INV,INV
46,AUTO-MDCK-2026-04,cell automation,NaN,NCGC00348147-04,3.187279,17.979592,5.789142,105.401946,65.822874,NaN,...,NaN,Average Total MDCK studies,NCGC00348147,2.517738,31.599763,21.265194,81.122566,55.120514,INV,INV

In [14]:
comp.to_excel("No AB, High BA.xlsx", index=False)

In [18]:
comp2 = pd.read_excel( 'AUTO-MDCK vs old MDCK studies.xlsx', sheet_name='C2 & Average MDCK' )
comp2

,Study,Project 04,Requester 04,Sample 04,Papp AB 04,Papp BA 04,Efflux 04,Recovery AB 04,Recovery BA 04,Unnamed: 9,...,Recovery AB 02,Recovery BA 02,Unnamed: 19,Study all,Sample all,Papp AB all,Papp BA all,Efflux all,Recovery AB all,Recovery BA all
0,AUTO-MDCK-C2-2026-04,cell automation,Propanolol,NCGC00015798-1,19.762651,3.661331,0.319149,61.665819,9.884906,NaN,...,43.51,64.05,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN
1,AUTO-MDCK-C2-2026-04,cell automation,Talinolol,NCGC00164542-02,0.105306,5.011658,61.767502,85.261774,63.944214,NaN,...,72.26,74.49,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN
2,AUTO-MDCK-C2-2026-04,cell automation,Quinidine,NCGC00166281-06,5.934260,48.784111,8.645525,53.574812,84.929267,NaN,...,33.99,33.11,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN
3,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351232-03,100.998743,0.586610,0.149467,138.651075,33.269934,NaN,...,NaN,530.58,NaN,Average Total MDCK studies,NCGC00351232,2.511223,10.138341,7.426439,59.760330,41.755578
4,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351432-03,6.284636,11.213129,1.837950,87.061448,59.530715,NaN,...,92.17,52.38,NaN,Average Total MDCK studies,NCGC00351432,3.191667,26.465212,10.498153,81.228333,61.550241
5,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351597-02,NaN,0.372000,NaN,73.564233,77.815314,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00351597,0.369599,6.605215,18.182062,91.680951,NaN
6,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351683-06,NaN,4.125345,NaN,96.763000,81.321745,NaN,...,87.47,77.31,NaN,Average Total MDCK studies,NCGC00351683,0.783333,11.226125,55.215970,82.695000,76.829753
7,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351982-04,NaN,3.302870,NaN,84.112843,60.189007,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00351982,NaN,56.030000,NaN,NaN,58.175000
8,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00356031-02,1.630378,9.953849,7.652621,68.438141,61.333058,NaN,...,55.52,59.02,NaN,Average Total MDCK studies,NCGC00356031,0.541294,12.338293,44.144574,100.521827,74.535199
9,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00356581-02,NaN,5.173314,NaN,148.151600,31.633687,NaN,...,NaN,211.39,NaN,Average Total MDCK studies,NCGC00356581,NaN,4.315000,NaN,NaN,30.500000
10,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00356803-02,NaN,0.970444,NaN,73.545375,61.917795,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00356803,221.515000,NaN,NaN,417.500000,NaN
11,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00370678-02,12.719609,18.219556,1.431621,66.392663,56.783902,NaN,...,94.32,61.39,NaN,Average Total MDCK studies,NCGC00370678,8.530488,50.465871,5.053858,72.485938,60.675183
12,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371072-06,2.687387,23.391593,8.712061,101.388893,69.105215,NaN,...,NaN,49.90,NaN,Average Total MDCK studies,NCGC00371072,1.160000,32.500000,27.870000,77.000000,72.500000
13,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371131-08,29.532238,6.127224,0.207668,82.797650,50.444086,NaN,...,79.66,51.33,NaN,Average Total MDCK studies,NCGC00371131,11.295000,6.140000,0.540000,78.000000,47.500000
14,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371157-01,NaN,1.094420,NaN,71.432963,57.329137,NaN,...,NaN,166.96,NaN,Average Total MDCK studies,NCGC00371157,NaN,1.705000,NaN,NaN,73.500000
15,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371404-02,12.347703,0.884544,0.078845,53.116386,39.699574,NaN,...,NaN,53.15,NaN,Average Total MDCK studies,NCGC00371404,0.402636,1.273804,4.027624,39.421226,43.000000
16,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371477-01,3.470194,0.226917,0.066832,35.974825,48.404737,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00371477,0.775000,0.811558,20.865000,27.380000,47.373126
17,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00373033-11,77.096492,20.274548,0.445807,166.378357,64.046329,NaN,...,32.62,25.81,NaN,Average Total MDCK studies,NCGC00373033,2.005000,5.220000,2.615000,62.500000,54.000000
18,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00378227-03,21.469293,42.278129,4.873890,51.451469,125.237582,NaN,...,48.07,30.82,NaN,Average Total MDCK studies,NCGC00378227,NaN,10.625000,NaN,NaN,66.500000
19,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00378556-03,2.538821,4.988728,2.011731,56.663542,62.669738,NaN,...,64.35,55.05,NaN,Average Total MDCK studies,NCGC00378556,1.930000,6.530000,3.385000,64.000000,63.500000
20,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00378599-02,1.023886,17.064498,16.669984,85.101338,73.543513,NaN,...,87.58,78.99,NaN,Average Total MDCK studies,NCGC00378599,0.570000,22.520000,40.085000,73.500000,75.500000
21,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00378612-02,0.970814,5.224159,5.232281,63.039163,60.718173,NaN,...,77.27,63.32,NaN,Average Total MDCK studies,NCGC00378612,1.150000,8.430000,7.360000,69.000000,69.500000
22,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00384179-01,1.317591,2.472622,1.909063,93.371372,60.476282,NaN,...,NaN,65.30,NaN,Average Total MDCK studies,NCGC00384179,1.435000,3.485000,2.415000,75.500000,51.500000
23,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00384250-01,NaN,NaN,NaN,0.000000,37.469510,NaN,...,NaN,40.50,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN
24,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00384450-01,1.497705,3.508907,2.526828,31.064839,46.854847,NaN,...,47.10,57.70,NaN,Average Total MDCK studies,NCGC00384450,5.239281,29.199503,6.050192,60.468675,69.480406
25,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00386123-03,5.502404,28.259552,5.148363,89.783587,68.248385,NaN,...,107.40,72.11,NaN,Average Total MDCK studies,NCGC00386123,4.342500,82.492500,27.500000,79.145000,70.202500
26,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00386182-02,1.526301,18.454114,12.168885,86.336058,66.127235,NaN,...,107.20,59.95,NaN,Average Total MDCK studies,NCGC00386182,NaN,24.170000,NaN,NaN,81.500000
27,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00387184-01,8.922165,11.284879,1.272235,67.844379,63.201625,NaN,...,88.75,65.47,NaN,Average Total MDCK studies,NCGC00387184,1.950000,8.005000,4.110000,59.000000,63.000000
28,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00387824-02,297.568148,102.367892,0.353389,550.282850,185.414706,NaN,...,273.18,76.10,NaN,Average Total MDCK studies,NCGC00387824,NaN,0.330000,NaN,NaN,57.000000
29,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00387853-04,0.750303,17.847797,24.271148,91.993368,62.930301,NaN,...,121.28,119.62,NaN,Average Total MDCK studies,NCGC00387853,0.700000,18.680000,27.070000,72.000000,63.500000
30,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00389131-03,14.318038,8.148160,0.678588,52.496683,32.825840,NaN,...,21.68,34.15,NaN,Average Total MDCK studies,NCGC00389131,13.940000,16.740000,1.220000,80.775000,64.080000
31,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00389998-02,60.483388,10.508915,0.187701,112.399345,28.886184,NaN,...,57.74,34.39,NaN,Average Total MDCK studies,NCGC00389998,16.610000,27.155000,1.640000,76.270000,69.870000
32,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00390533-01,NaN,NaN,NaN,0.000000,113.912914,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00390533,NaN,11.705000,NaN,NaN,30.500000
33,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00390633-01,NaN,1.045049,NaN,75.397285,68.749633,NaN,...,NaN,71.96,NaN,Average Total MDCK studies,NCGC00390633,NaN,8.735000,NaN,NaN,76.500000
34,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00390768-03,28.243318,0.740372,0.016938,41.657015,31.417499,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00390768,0.605000,0.290000,0.695000,36.000000,45.000000
35,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00408793-02,NaN,9.428822,NaN,145.647230,31.381565,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00408793,NaN,9.480000,NaN,NaN,34.500000
36,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00411866-03,NaN,1.380078,NaN,59.691973,39.196193,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00411866,0.385000,1.280000,3.345000,70.160000,50.410000
37,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00413972-04,5.752545,19.502341,3.390918,59.242754,54.289014,NaN,...,74.28,53.00,NaN,Average Total MDCK studies,NCGC00413972,6.067500,33.230000,5.320000,84.195000,72.837500
38,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00414939-01,NaN,NaN,NaN,0.000000,0.000000,NaN,...,NaN,NaN,NaN,Average Total MDCK studies,NCGC00414939,NaN,NaN,NaN,NaN,NaN
39,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00420895-02,NaN,22.338314,NaN,48.891058,55.021146,NaN,...,NaN,49.96,NaN,Average Total MDCK studies,NCGC00420895,10.990000,29.430000,2.730000,92.500000,75.500000
40,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00440110-01,6.034205,8.983240,1.529731,83.559871,58.204430,NaN,...,88.82,56.54,NaN,Average Total MDCK studies,NCGC00440110,6.850000,50.157500,5.990000,71.065000,75.505000
41,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00446653-01,19.997319,18.750195,0.955620,79.070127,66.232549,NaN,...,93.54,58.53,NaN,Average Total MDCK studies,NCGC00446653,14.900000,19.900000,1.350000,90.200000,65.800000
42,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00475742-03,3.892360,20.685580,5.380240,90.462802,63.000015,NaN,...,70.23,58.00,NaN,Average Total MDCK studies,NCGC00475742,2.605000,27.510000,10.585000,63.000000,74.500000
43,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00480721-02,NaN,3.073754,NaN,117.877250,84.561445,NaN,...,109.15,76.78,NaN,Average Total MDCK studies,NCGC00480721,0.120000,0.840000,7.095000,68.500000,57.000000
44,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00481329-01,3.188588,75.691308,9.421731,11.282702,153.138941,NaN,...,NaN,22.80,NaN,Average Total MDCK studies,NCGC00481329,10.185000,71.975000,10.235000,61.720000,64.592500
45,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00481516-01,14.077720,13.443649,0.957605,40.830238,33.934270,NaN,...,92.09,22.48,NaN,Average Total MDCK studies,NCGC00481516,13.585000,23.150000,1.700000,77.500000,65.000000
46,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00483973-01,NaN,63.241581,NaN,8.486838,114.872024,NaN,...,24.73,33.14,NaN,Average Total MDCK studies,NCGC00483973,7.495000,22.980000,3.980000,71.500000,58.500000
47,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00484800-02,319.567694,100.422297,0.324228,570.241072,170.199626,NaN,...,209.65,72.20,NaN,Average Total MDCK studies,NCGC00484800,233.730000,56.985000,0.245000,449.000000,110.000000

In [19]:
comp2["C2 No AB 04 high BA 04"] = np.where(
    comp2["Papp AB 04"].isna() & (comp2["Papp BA 04"] >=6),
    "no AB high BA",
    "INV"
)
comp2["C2 No AB 02 high BA 02"] = np.where(
    comp2["Papp AB 02"].isna() & (comp2["Papp BA 02"] >= 6),
    "no AB high BA",
    "INV"
)
comp2

,Study,Project 04,Requester 04,Sample 04,Papp AB 04,Papp BA 04,Efflux 04,Recovery AB 04,Recovery BA 04,Unnamed: 9,...,Unnamed: 19,Study all,Sample all,Papp AB all,Papp BA all,Efflux all,Recovery AB all,Recovery BA all,C2 No AB 04 high BA 04,C2 No AB 02 high BA 02
0,AUTO-MDCK-C2-2026-04,cell automation,Propanolol,NCGC00015798-1,19.762651,3.661331,0.319149,61.665819,9.884906,NaN,...,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN,INV,INV
1,AUTO-MDCK-C2-2026-04,cell automation,Talinolol,NCGC00164542-02,0.105306,5.011658,61.767502,85.261774,63.944214,NaN,...,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN,INV,INV
2,AUTO-MDCK-C2-2026-04,cell automation,Quinidine,NCGC00166281-06,5.934260,48.784111,8.645525,53.574812,84.929267,NaN,...,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN,INV,INV
3,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351232-03,100.998743,0.586610,0.149467,138.651075,33.269934,NaN,...,NaN,Average Total MDCK studies,NCGC00351232,2.511223,10.138341,7.426439,59.760330,41.755578,INV,no AB high BA
4,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351432-03,6.284636,11.213129,1.837950,87.061448,59.530715,NaN,...,NaN,Average Total MDCK studies,NCGC00351432,3.191667,26.465212,10.498153,81.228333,61.550241,INV,INV
5,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351597-02,NaN,0.372000,NaN,73.564233,77.815314,NaN,...,NaN,Average Total MDCK studies,NCGC00351597,0.369599,6.605215,18.182062,91.680951,NaN,INV,INV
6,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351683-06,NaN,4.125345,NaN,96.763000,81.321745,NaN,...,NaN,Average Total MDCK studies,NCGC00351683,0.783333,11.226125,55.215970,82.695000,76.829753,INV,INV
7,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00351982-04,NaN,3.302870,NaN,84.112843,60.189007,NaN,...,NaN,Average Total MDCK studies,NCGC00351982,NaN,56.030000,NaN,NaN,58.175000,INV,INV
8,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00356031-02,1.630378,9.953849,7.652621,68.438141,61.333058,NaN,...,NaN,Average Total MDCK studies,NCGC00356031,0.541294,12.338293,44.144574,100.521827,74.535199,INV,INV
9,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00356581-02,NaN,5.173314,NaN,148.151600,31.633687,NaN,...,NaN,Average Total MDCK studies,NCGC00356581,NaN,4.315000,NaN,NaN,30.500000,INV,no AB high BA
10,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00356803-02,NaN,0.970444,NaN,73.545375,61.917795,NaN,...,NaN,Average Total MDCK studies,NCGC00356803,221.515000,NaN,NaN,417.500000,NaN,INV,INV
11,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00370678-02,12.719609,18.219556,1.431621,66.392663,56.783902,NaN,...,NaN,Average Total MDCK studies,NCGC00370678,8.530488,50.465871,5.053858,72.485938,60.675183,INV,INV
12,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371072-06,2.687387,23.391593,8.712061,101.388893,69.105215,NaN,...,NaN,Average Total MDCK studies,NCGC00371072,1.160000,32.500000,27.870000,77.000000,72.500000,INV,no AB high BA
13,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371131-08,29.532238,6.127224,0.207668,82.797650,50.444086,NaN,...,NaN,Average Total MDCK studies,NCGC00371131,11.295000,6.140000,0.540000,78.000000,47.500000,INV,INV
14,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371157-01,NaN,1.094420,NaN,71.432963,57.329137,NaN,...,NaN,Average Total MDCK studies,NCGC00371157,NaN,1.705000,NaN,NaN,73.500000,INV,INV
15,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371404-02,12.347703,0.884544,0.078845,53.116386,39.699574,NaN,...,NaN,Average Total MDCK studies,NCGC00371404,0.402636,1.273804,4.027624,39.421226,43.000000,INV,INV
16,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00371477-01,3.470194,0.226917,0.066832,35.974825,48.404737,NaN,...,NaN,Average Total MDCK studies,NCGC00371477,0.775000,0.811558,20.865000,27.380000,47.373126,INV,INV
17,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00373033-11,77.096492,20.274548,0.445807,166.378357,64.046329,NaN,...,NaN,Average Total MDCK studies,NCGC00373033,2.005000,5.220000,2.615000,62.500000,54.000000,INV,INV
18,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00378227-03,21.469293,42.278129,4.873890,51.451469,125.237582,NaN,...,NaN,Average Total MDCK studies,NCGC00378227,NaN,10.625000,NaN,NaN,66.500000,INV,INV
19,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00378556-03,2.538821,4.988728,2.011731,56.663542,62.669738,NaN,...,NaN,Average Total MDCK studies,NCGC00378556,1.930000,6.530000,3.385000,64.000000,63.500000,INV,INV
20,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00378599-02,1.023886,17.064498,16.669984,85.101338,73.543513,NaN,...,NaN,Average Total MDCK studies,NCGC00378599,0.570000,22.520000,40.085000,73.500000,75.500000,INV,INV
21,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00378612-02,0.970814,5.224159,5.232281,63.039163,60.718173,NaN,...,NaN,Average Total MDCK studies,NCGC00378612,1.150000,8.430000,7.360000,69.000000,69.500000,INV,INV
22,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00384179-01,1.317591,2.472622,1.909063,93.371372,60.476282,NaN,...,NaN,Average Total MDCK studies,NCGC00384179,1.435000,3.485000,2.415000,75.500000,51.500000,INV,INV
23,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00384250-01,NaN,NaN,NaN,0.000000,37.469510,NaN,...,NaN,Average Total MDCK studies,NaN,NaN,NaN,NaN,NaN,NaN,INV,INV
24,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00384450-01,1.497705,3.508907,2.526828,31.064839,46.854847,NaN,...,NaN,Average Total MDCK studies,NCGC00384450,5.239281,29.199503,6.050192,60.468675,69.480406,INV,INV
25,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00386123-03,5.502404,28.259552,5.148363,89.783587,68.248385,NaN,...,NaN,Average Total MDCK studies,NCGC00386123,4.342500,82.492500,27.500000,79.145000,70.202500,INV,INV
26,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00386182-02,1.526301,18.454114,12.168885,86.336058,66.127235,NaN,...,NaN,Average Total MDCK studies,NCGC00386182,NaN,24.170000,NaN,NaN,81.500000,INV,INV
27,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00387184-01,8.922165,11.284879,1.272235,67.844379,63.201625,NaN,...,NaN,Average Total MDCK studies,NCGC00387184,1.950000,8.005000,4.110000,59.000000,63.000000,INV,INV
28,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00387824-02,297.568148,102.367892,0.353389,550.282850,185.414706,NaN,...,NaN,Average Total MDCK studies,NCGC00387824,NaN,0.330000,NaN,NaN,57.000000,INV,INV
29,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00387853-04,0.750303,17.847797,24.271148,91.993368,62.930301,NaN,...,NaN,Average Total MDCK studies,NCGC00387853,0.700000,18.680000,27.070000,72.000000,63.500000,INV,INV
30,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00389131-03,14.318038,8.148160,0.678588,52.496683,32.825840,NaN,...,NaN,Average Total MDCK studies,NCGC00389131,13.940000,16.740000,1.220000,80.775000,64.080000,INV,INV
31,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00389998-02,60.483388,10.508915,0.187701,112.399345,28.886184,NaN,...,NaN,Average Total MDCK studies,NCGC00389998,16.610000,27.155000,1.640000,76.270000,69.870000,INV,INV
32,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00390533-01,NaN,NaN,NaN,0.000000,113.912914,NaN,...,NaN,Average Total MDCK studies,NCGC00390533,NaN,11.705000,NaN,NaN,30.500000,INV,INV
33,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00390633-01,NaN,1.045049,NaN,75.397285,68.749633,NaN,...,NaN,Average Total MDCK studies,NCGC00390633,NaN,8.735000,NaN,NaN,76.500000,INV,INV
34,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00390768-03,28.243318,0.740372,0.016938,41.657015,31.417499,NaN,...,NaN,Average Total MDCK studies,NCGC00390768,0.605000,0.290000,0.695000,36.000000,45.000000,INV,INV
35,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00408793-02,NaN,9.428822,NaN,145.647230,31.381565,NaN,...,NaN,Average Total MDCK studies,NCGC00408793,NaN,9.480000,NaN,NaN,34.500000,no AB high BA,INV
36,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00411866-03,NaN,1.380078,NaN,59.691973,39.196193,NaN,...,NaN,Average Total MDCK studies,NCGC00411866,0.385000,1.280000,3.345000,70.160000,50.410000,INV,INV
37,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00413972-04,5.752545,19.502341,3.390918,59.242754,54.289014,NaN,...,NaN,Average Total MDCK studies,NCGC00413972,6.067500,33.230000,5.320000,84.195000,72.837500,INV,INV
38,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00414939-01,NaN,NaN,NaN,0.000000,0.000000,NaN,...,NaN,Average Total MDCK studies,NCGC00414939,NaN,NaN,NaN,NaN,NaN,INV,no AB high BA
39,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00420895-02,NaN,22.338314,NaN,48.891058,55.021146,NaN,...,NaN,Average Total MDCK studies,NCGC00420895,10.990000,29.430000,2.730000,92.500000,75.500000,no AB high BA,no AB high BA
40,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00440110-01,6.034205,8.983240,1.529731,83.559871,58.204430,NaN,...,NaN,Average Total MDCK studies,NCGC00440110,6.850000,50.157500,5.990000,71.065000,75.505000,INV,INV
41,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00446653-01,19.997319,18.750195,0.955620,79.070127,66.232549,NaN,...,NaN,Average Total MDCK studies,NCGC00446653,14.900000,19.900000,1.350000,90.200000,65.800000,INV,INV
42,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00475742-03,3.892360,20.685580,5.380240,90.462802,63.000015,NaN,...,NaN,Average Total MDCK studies,NCGC00475742,2.605000,27.510000,10.585000,63.000000,74.500000,INV,INV
43,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00480721-02,NaN,3.073754,NaN,117.877250,84.561445,NaN,...,NaN,Average Total MDCK studies,NCGC00480721,0.120000,0.840000,7.095000,68.500000,57.000000,INV,INV
44,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00481329-01,3.188588,75.691308,9.421731,11.282702,153.138941,NaN,...,NaN,Average Total MDCK studies,NCGC00481329,10.185000,71.975000,10.235000,61.720000,64.592500,INV,INV
45,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00481516-01,14.077720,13.443649,0.957605,40.830238,33.934270,NaN,...,NaN,Average Total MDCK studies,NCGC00481516,13.585000,23.150000,1.700000,77.500000,65.000000,INV,INV
46,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00483973-01,NaN,63.241581,NaN,8.486838,114.872024,NaN,...,NaN,Average Total MDCK studies,NCGC00483973,7.495000,22.980000,3.980000,71.500000,58.500000,no AB high BA,INV
47,AUTO-MDCK-C2-2026-04,NaN,NaN,NCGC00484800-02,319.567694,100.422297,0.324228,570.241072,170.199626,NaN,...,NaN,Average Total MDCK studies,NCGC00484800,233.730000,56.985000,0.245000,449.000000,110.000000,INV,INV

In [20]:
comp2.to_excel("C2 No AB, High BA.xlsx", index = False)